  application:
    name: "bank-spring-app"
  jpa:
    database: MYSQL
    show-sql: true
  database:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_db?useSSL=false
    username: "root"
    password: "root"